version: '3'

services:

  varnish:
    container_name: 'rizzanet-varnish'
    build: ./docker/varnish/
    ports:
      - '81:81'
    env_file:
      - './docker/varnish/rizzanet_varnish.env'
    volumes:
      - './docker/varnish/scripts/default-template.vcl:/scripts/default-template.vcl'
    depends_on:
      - web
    
  web:
    container_name: 'rizzanet-web'
    image: 'ryanolee/rizzanet:dev'
    build: .
    ports:
     - "80:8080"
    volumes:
      - '.:/app/'
    env_file:
      - ./docker/rizzanet/rizzanet.env
    depends_on:
      - es
  
  es:
    container_name: 'rizzanet-es'
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.3.2'
    ports:
      - '9200:9200'
    expose:
      - 9200
  
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    environment:
      SERVER_NAME: es
      ELASTICSEARCH_URL: 'http://es:9200'
    ports:
      - '9201:5601'
    depends_on:
      - es
  
  db:
    image: postgres
    expose: 
      - 5432
    ports:
      - '3307:5432'
    env_file:
      - ./docker/postgres/postgres.env